### ISSUE TITLE
已使用，很棒的脚本。

### ISSUE THREAD

**Issue by XuanXiaoming** [YukkuriC/steam-anti-lock#1]
![image](https://user-images.githubusercontent.com/10046849/79164831-72482d80-7e14-11ea-932f-593fdfcab760.png)

**Comment by YukkuriC** [comment]
保重身体（笑
嘛……基本小黄油类锁区的游戏其实有widget就能买了来着，后面的更新都是针对瘟疫公司一个游戏写的（
